version: 0.2
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=azuredevsecopsorgmine -Dsonar.projectKey=azuredevsecopsorgmine -Dsonar.login=bb40677fd0de74f3a2bb7dca424ff995402321f2 
      
