version: 0.2
phases:
  install:
    runtime-versions:
      java: latest
    commands:
      - curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
  build:
    commands:
      # Análise Semgrep
      - docker run --rm -v $CODEBUILD_SRC_DIR:/src returntocorp/semgrep semgrep --config=auto --json --output=/src/semgrep-report.json /src
      # Análise Horusec
      - horusec start -p $CODEBUILD_SRC_DIR -o json -O horusec-report.json -D
artifacts:
  files:
    - semgrep-report.json
    - horusec-report.json
